version: "3.9"

services:
  ct_task_router:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ct_task_router
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/config.json:ro
      - ./.secrets.json:/.secrets.json:ro
      - ./logs:/logs
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - vault
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: test-root-token
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

volumes:
  redis_data:
